/**
 * 错误代码枚举
 */
export enum ErrorCode {
    // LLM错误
    RATE_LIMIT = 'RATE_LIMIT',
    TIMEOUT = 'TIMEOUT',
    INVALID_MODEL = 'INVALID_MODEL',
    INVALID_REQUEST = 'INVALID_REQUEST',

    // 工具错误
    TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
    TOOL_EXECUTION_ERROR = 'TOOL_EXECUTION_ERROR',
    TOOL_PERMISSION_DENIED = 'TOOL_PERMISSION_DENIED',

    // 缓存错误
    CACHE_ERROR = 'CACHE_ERROR',
    CACHE_MISS = 'CACHE_MISS',

    // Agent错误
    AGENT_EXECUTION_ERROR = 'AGENT_EXECUTION_ERROR',
    AGENT_TIMEOUT = 'AGENT_TIMEOUT',
    AGENT_ABORTED = 'AGENT_ABORTED',

    // Socket错误
    SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR',
    SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED',

    // 通用错误
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}
